### ISSUE TITLE
Error when I click the gradio Infer button under Windows

### ISSUE THREAD

**Issue by SoftologyPro** [shubham-goel/4D-Humans#105]
```
Traceback (most recent call last):
  File "D:\Tests\4D-Humans\voc_4dhumans\lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "D:\Tests\4D-Humans\voc_4dhumans\lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\Tests\4D-Humans\voc_4dhumans\lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
  File "D:\Tests\4D-Humans\voc_4dhumans\lib\site-packages\gradio\blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Tests\4D-Humans\voc_4dhumans\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\Tests\4D-Humans\voc_4dhumans\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "D:\Tests\4D-Humans\voc_4dhumans\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "D:\Tests\4D-Humans\voc_4dhumans\lib\site-packages\gradio\utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
  File "D:\Tests\4D-Humans\gradio_app.py", line 145, in infer
    cam_view = renderer.render_rgba_multiple(all_verts, cam_t=all_cam_t, render_res=img_size[n], **misc_args)
  File "D:\Tests\4D-Humans\hmr2\utils\renderer.py", line 327, in render_rgba_multiple
    renderer = pyrender.OffscreenRenderer(viewport_width=render_res[0],
  File "D:\Tests\4D-Humans\voc_4dhumans\lib\site-packages\pyrender\offscreen.py", line 31, in __init__
    self._create()
  File "D:\Tests\4D-Humans\voc_4dhumans\lib\site-packages\pyrender\offscreen.py", line 149, in _create
    self._platform.init_context()
  File "D:\Tests\4D-Humans\voc_4dhumans\lib\site-packages\pyrender\platforms\pyglet_platform.py", line 50, in init_context
    self._window = pyglet.window.Window(config=conf, visible=False,
  File "D:\Tests\4D-Humans\voc_4dhumans\lib\site-packages\pyglet\window\win32\__init__.py", line 104, in __init__
    super(Win32Window, self).__init__(*args, **kwargs)
  File "D:\Tests\4D-Humans\voc_4dhumans\lib\site-packages\pyglet\window\__init__.py", line 536, in __init__
    config = screen.get_best_config(config)
  File "D:\Tests\4D-Humans\voc_4dhumans\lib\site-packages\pyglet\canvas\base.py", line 162, in get_best_config
    configs = self.get_matching_configs(template)
  File "D:\Tests\4D-Humans\voc_4dhumans\lib\site-packages\pyglet\canvas\win32.py", line 36, in get_matching_configs
    configs = template.match(canvas)
  File "D:\Tests\4D-Humans\voc_4dhumans\lib\site-packages\pyglet\gl\win32.py", line 22, in match
    return self._get_arb_pixel_format_matching_configs(canvas)
  File "D:\Tests\4D-Humans\voc_4dhumans\lib\site-packages\pyglet\gl\win32.py", line 93, in _get_arb_pixel_format_matching_configs
    wglext_arb.wglChoosePixelFormatARB(canvas.hdc, attrs, None, nformats, pformats, nformats)
  File "D:\Tests\4D-Humans\voc_4dhumans\lib\site-packages\pyglet\gl\lib_wgl.py", line 66, in __call__
    return self.func(*args, **kwargs)
  File "D:\Tests\4D-Humans\voc_4dhumans\lib\site-packages\pyglet\gl\lib.py", line 25, in MissingFunction
    raise MissingFunctionException(name, requires, suggestions)
pyglet.gl.lib.MissingFunctionException: wglChoosePixelFormatARB is not exported by the available OpenGL driver.  ARB_pixel_format is required for this functionality.
```

Any ideas on how to fix this?
voc_4dhumans is the Python venv I setup for testing.

**Comment by geopavlakos** [comment]
Unfortunately, we cannot test 4D Humans on windows, but please take a look at issues #12 and #36 where people report their experience with windows platforms.
