### ISSUE TITLE
A bug of OpenGL_accelerate?

### ISSUE THREAD

**Issue by tensorboy** [shubham-goel/4D-Humans#15]
the command:
```
python track.py video.source="example_data/videos/gymnasts.mp4"
```
sometimes output:
```
Tracking : gymnasts 🏃  ━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  21% eta : 0:03:05  time elapsed : 0:00:50
GLError(
        err = 1282,
        description = b'invalid operation',
        baseOperation = glBindVertexArray,
        cArguments = (4,)
)
Traceback (most recent call last):
  File "/home/tensorboy/PHALP/phalp/trackers/PHALP.py", line 252, in track
    rendered_, f_size = self.visualizer.render_video(final_visuals_dic[frame_key])
  File "/home/tensorboy/PHALP/phalp/visualize/visualizer.py", line 350, in render_video
    rendered_image_final, valid_mask  = self.render_single_frame(
  File "/home/tensorboy/PHALP/phalp/visualize/visualizer.py", line 77, in render_single_frame
    rgb_from_pred, validmask = self.render.visualize_all(pred_vertices.numpy(), pred_cam_t_bs.cpu().numpy(), color, image, use_image=use_image)
  File "/home/tensorboy/PHALP/phalp/visualize/py_renderer.py", line 116, in visualize_all
    color = self.__call__(verts, focal_length=fl, baseColorFactors=baseColorFactors)
  File "/home/tensorboy/PHALP/phalp/visualize/py_renderer.py", line 153, in __call__
    color, rend_depth = self.renderer.render(scene, flags=pyrender.RenderFlags.RGBA)
  File "/home/tensorboy/anaconda3/envs/pose/lib/python3.10/site-packages/pyrender/offscreen.py", line 102, in render
    retval = self._renderer.render(scene, flags, seg_node_map)
  File "/home/tensorboy/anaconda3/envs/pose/lib/python3.10/site-packages/pyrender/renderer.py", line 144, in render
    retval = self._forward_pass(scene, flags, seg_node_map=seg_node_map)
  File "/home/tensorboy/anaconda3/envs/pose/lib/python3.10/site-packages/pyrender/renderer.py", line 389, in _forward_pass
    self._bind_and_draw_primitive(
  File "/home/tensorboy/anaconda3/envs/pose/lib/python3.10/site-packages/pyrender/renderer.py", line 516, in _bind_and_draw_primitive
    primitive._bind()
  File "/home/tensorboy/anaconda3/envs/pose/lib/python3.10/site-packages/pyrender/primitive.py", line 441, in _bind
    glBindVertexArray(self._vaid)
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'invalid operation',
        baseOperation = glBindVertexArray,
        cArguments = (4,)
)

```

sometimes the error will happen at 10%, sometimes 5%.

Anyone have some suggestions?

**Comment by tensorboy** [comment]
a issue of pyrenderer: https://cwang.me/wiki/pyrender/
