### ISSUE TITLE
run track.py always throw this cuda error

### ISSUE THREAD

**Issue by Justinitaa** [shubham-goel/4D-Humans#152]
there is a error when i run track.py with a video:
Traceback (most recent call last):
  File "/root/4D-Humans/PHALP-master/phalp/trackers/PHALP.py", line 197, in track
    pred_bbox, pred_bbox_pad, pred_masks, pred_scores, pred_classes, gt_tids, gt_annots = self.get_detections(image_frame, frame_name, t_, additional_data, measurments)
  File "/root/4D-Humans/track.py", line 161, in get_detections
    ) =  super().get_detections(image, frame_name, t_, additional_data, measurments)
  File "/root/4D-Humans/PHALP-master/phalp/trackers/PHALP.py", line 333, in get_detections
    outputs     = self.detector(image)
  File "/root/4D-Humans/PHALP-master/phalp/utils/utils_detectron2.py", line 216, in __call__
    predictions = self.model([inputs])[0]
  File "/root/miniconda3/envs/ENV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 150, in forward
    return self.inference(batched_inputs)
  File "/root/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 203, in inference
    images = self.preprocess_image(batched_inputs)
  File "/root/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 228, in preprocess_image
    images = [(x - self.pixel_mean) / self.pixel_std for x in images]
  File "/root/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 228, in <listcomp>
    images = [(x - self.pixel_mean) / self.pixel_std for x in images]
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
how can i resolve it?

**Comment by geopavlakos** [comment]
This looks like a problem with the environment you are using. Can you create the environment again and make sure you are not getting any errors?
