### ISSUE TITLE
Parameters in the smpl_mean_params.npz file

### ISSUE THREAD

**Issue by 1309723614** [shubham-goel/4D-Humans#17]
Hello author, thanks for your excellent work. 

But I have a problem: 
I noticed that I downloaded a file from the project [brjathu/PHALP](https://github.com/brjathu/PHALP/blob/475b1d191d45fb5703cb3f8f1c02212a0c05dc6d/phalp/trackers/PHALP.py#L620). In 4dhumans, this file data is used only for the first 24 items of ['pose'] parameters, namely global_orient ([:, [0]]) and body_pose ([:, 1:]). I would like to know what the following parameters [24:] mean.

Please reply to me at your earliest convenience. Thanks a million.

**Comment by 1309723614** [comment]
I made a mistake. It should be body_pose ([:, 1:24]).

**Comment by 1309723614** [comment]
https://github.com/brjathu/PHALP/issues/17

**Comment by ouusan** [comment]
Hello, when i run the train.py , The following error occurs : 
Traceback (most recent call last):
  File "/root/4D-Humans/train.py", line 107, in main
    train(cfg)
  File "/root/4D-Humans/hmr2/utils/misc.py", line 42, in wrap
    raise ex
  File "/root/4D-Humans/hmr2/utils/misc.py", line 39, in wrap
    ret = task_func(cfg=cfg)
  File "/root/4D-Humans/train.py", line 57, in train
    model = HMR2(cfg)
  File "/root/4D-Humans/hmr2/models/hmr2.py", line 39, in __init__
    self.smpl_head = build_smpl_head(cfg)
  File "/root/4D-Humans/hmr2/models/heads/smpl_head.py", line 13, in build_smpl_head
    return SMPLTransformerDecoderHead(cfg)
  File "/root/4D-Humans/hmr2/models/heads/smpl_head.py", line 49, in __init__
    mean_params = np.load(cfg.SMPL.MEAN_PARAMS)
  File "/usr/local/lib/python3.10/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/4DHumans/data//smpl_mean_params.npz'
smpl_mean_params.npz file

I would ilke to ask how can i get this smpl_mean_params.npz file ?
Thankyou ! Looking forward to your reply.

**Comment by geopavlakos** [comment]
This is downloaded for you the first time you run the demo code. You can check also [this function](https://github.com/shubham-goel/4D-Humans/blob/a6532b0c2e2747330eb9ae6ef2595eef347f1b24/hmr2/models/__init__.py#L9).
