### ISSUE TITLE
.cache

### ISSUE THREAD

**Issue by yarinlevy1018** [shubham-goel/4D-Humans#23]
hi, I'm new in python, and when I try to run your code I get this error:
Traceback (most recent call last):
      File "C:\Users\tamir\4D-Humans\track.py", line 9, in <module>
          from phalp.configs.base import FullConfig
     File "C:\Users\tamir\anaconda3\envs\4D-humans\lib\site-packages\phalp\configs\base.py", line 8, in <module>
          CACHE_DIR = os.path.join(os.environ.get("HOME"), ".cache")  # None if the variable does not exist
     File "C:\Users\tamir\anaconda3\envs\4D-humans\lib\ntpath.py", line 104, in join
           path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

this error appears when I run tracking on video and also when I run the demo code I get similar error.
the environment building was well.
how to fix this?

**Comment by geopavlakos** [comment]
It looks like you have a windows environment. You might want to check a previous issue #12, where a windows user shares some advice on what needs to change to run 4D Humans smoothly on windows.
