### ISSUE TITLE
out of memory issue 

### ISSUE THREAD

**Issue by kotaxyz** [shubham-goel/4D-Humans#28]
i was wondering , does this works with 8gb vram gpus , i have been trying to infer using track.py and demo.py , i put a low quality image and tried but i only get oom error here is the error 

C:\Users\Genesis\anaconda3\envs\4D-Humans\lib\site-packages\torchaudio\backend\utils.py:74: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")
Lightning automatically upgraded your loaded checkpoint from v1.8.1 to v2.0.6. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file C:\Users\Genesis\.cache\4DHumans\logs\train\multiruns\hmr2\0\checkpoints\epoch=35-step=1000000.ckpt`
WARNING: You are using a SMPL model, with only 10 shape coefficients.
Traceback (most recent call last):
  File "C:\Users\Genesis\github\4D-Humans\demo.py", line 143, in <module>
    main()
  File "C:\Users\Genesis\github\4D-Humans\demo.py", line 59, in main
    det_out = detector(img_cv2)
  File "C:\Users\Genesis\github\4D-Humans\hmr2\utils\utils_detectron2.py", line 92, in __call__
    predictions = self.model([inputs])[0]
  File "C:\Users\Genesis\anaconda3\envs\4D-Humans\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Genesis\anaconda3\envs\4D-Humans\lib\site-packages\detectron2\modeling\meta_arch\rcnn.py", line 150, in forward
    return self.inference(batched_inputs)
  File "C:\Users\Genesis\anaconda3\envs\4D-Humans\lib\site-packages\detectron2\modeling\meta_arch\rcnn.py", line 204, in inference
    features = self.backbone(images.tensor)
  File "C:\Users\Genesis\anaconda3\envs\4D-Humans\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Genesis\anaconda3\envs\4D-Humans\lib\site-packages\detectron2\modeling\backbone\vit.py", line 489, in forward
    bottom_up_features = self.net(x)
  File "C:\Users\Genesis\anaconda3\envs\4D-Humans\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Genesis\anaconda3\envs\4D-Humans\lib\site-packages\detectron2\modeling\backbone\vit.py", line 357, in forward
    x = blk(x)
  File "C:\Users\Genesis\anaconda3\envs\4D-Humans\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Genesis\anaconda3\envs\4D-Humans\lib\site-packages\detectron2\modeling\backbone\vit.py", line 218, in forward
    x = self.attn(x)
  File "C:\Users\Genesis\anaconda3\envs\4D-Humans\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Genesis\anaconda3\envs\4D-Humans\lib\site-packages\detectron2\modeling\backbone\vit.py", line 75, in forward
    attn = add_decomposed_rel_pos(attn, q, self.rel_pos_h, self.rel_pos_w, (H, W), (H, W))
  File "C:\Users\Genesis\anaconda3\envs\4D-Humans\lib\site-packages\detectron2\modeling\backbone\utils.py", line 122, in add_decomposed_rel_pos
    attn.view(B, q_h, q_w, k_h, k_w) + rel_h[:, :, :, :, None] + rel_w[:, :, :, None, :]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 8.00 GiB total capacity; 6.38 GiB already allocated; 0 bytes free; 6.56 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by carlosedubarreto** [comment]
With some help I received, I was able to try something.
Changing the detector configuration from 'vitdet' to 'maskrcnn' made 4d humans to use less VRAM.

with maskrcnn I was able to run using a little bit more than 8gb 
![image](https://github.com/shubham-goel/4D-Humans/assets/4061130/5f17fa82-251c-4551-ab4a-7ec8a53a853d)


while using 'vitdet' it used more than 14gb
![image](https://github.com/shubham-goel/4D-Humans/assets/4061130/be42d14d-ea9b-44ac-8d70-919da1d66d76)


you can find this information to change at:
PAHLP/phalp/config/base.py
on line 38

![image](https://github.com/shubham-goel/4D-Humans/assets/4061130/4e952dd0-c8b5-4df0-aa4b-a471b9c8f952)
