### ISSUE TITLE
ImportError: cannot import name 'expand_bbox_to_aspect_ratio'

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [shubham-goel/4D-Humans#61]
When I run the 4DHumans.ipynb, the following error occurred.

```
!python track.py video.source="example_data/videos/gymnasts.mp4"

Traceback (most recent call last):
  File "/content/4D-Humans/track.py", line 11, in <module>
    from phalp.trackers.PHALP import PHALP
  File "/usr/local/lib/python3.10/dist-packages/phalp/trackers/PHALP.py", line 16, in <module>
    from hmr2.datasets.utils import expand_bbox_to_aspect_ratio
ImportError: cannot import name 'expand_bbox_to_aspect_ratio' from 'hmr2.datasets.utils' (/content/4D-Humans/hmr2/datasets/utils.py)
```

Please fix it!

**Comment by raincrash** [comment]
Temporarily, you can change line 16 to `from hmr2.datasets.utils import expand_to_aspect_ratio` to fix this.

**Comment by geopavlakos** [comment]
There was indeed a problem on colab that we have resolved now. Could you please try again?

**Comment by Ishihara-Masabumi** [comment]
OK, Thanks.
