### ISSUE TITLE
No such file or directory: 'data/smpl_mean_params.npz'

### ISSUE THREAD

**Issue by SoftologyPro** [shubham-goel/4D-Humans#7]
Created a venv, installed pre-reqs, downloaded and extracted the model, edited out the EGL lines as shown here https://github.com/shubham-goel/4D-Humans/issues/5, ran the example command

`python demo.py --img_folder example_data/images --out_folder demo_out --batch_size=48 --side_view`

get this

```
(venv) D:\4D-Humans>python demo.py --img_folder example_data/images --out_folder demo_out --batch_size=48 --side_view
Lightning automatically upgraded your loaded checkpoint from v1.8.1 to v2.0.2. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file D:\4D-Humans\logs\train\multiruns\hmr2\0\checkpoints\epoch=35-step=1000000.ckpt`
Traceback (most recent call last):
  File "D:\4D-Humans\demo.py", line 30, in <module>
    model = HMR2.load_from_checkpoint(args.checkpoint, strict=False, cfg=model_cfg).to(device)
  File "D:\4D-Humans\venv\lib\site-packages\pytorch_lightning\core\module.py", line 1531, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "D:\4D-Humans\venv\lib\site-packages\pytorch_lightning\core\saving.py", line 88, in _load_from_checkpoint
    storage = _load_state(cls, checkpoint, strict=strict, **kwargs)
  File "D:\4D-Humans\venv\lib\site-packages\pytorch_lightning\core\saving.py", line 141, in _load_state
    obj = cls(**_cls_kwargs)
  File "D:\4D-Humans\hmr2\models\hmr2.py", line 34, in __init__
    self.smpl_head = build_smpl_head(cfg)
  File "D:\4D-Humans\hmr2\models\heads\smpl_head.py", line 13, in build_smpl_head
    return SMPLTransformerDecoderHead(cfg)
  File "D:\4D-Humans\hmr2\models\heads\smpl_head.py", line 49, in __init__
    mean_params = np.load(cfg.SMPL.MEAN_PARAMS)
  File "D:\4D-Humans\venv\lib\site-packages\numpy\lib\npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/smpl_mean_params.npz'
```

I cannot find that npz file anywhere under the 4D-Humans directories.

**Comment by TheEliteGeek** [comment]
I got this error as well. I'm reinstalling again (after reinstalling Miniconda) but I remember getting similar errors. My thoughts now is that the ./fetch_data.sh doesn't actually download the required file. I'm going to manually download it to /4D-Humans and then run "tar -xvf hmr2_data.tar.gz" and see what happens. I think it might work based on the output so far:

```
PS M:\AIStuff\4D-Humans> tar -xvf hmr2_data.tar.gz
x logs/train/multiruns/hmr2/
x logs/train/multiruns/hmr2/0/
x logs/train/multiruns/hmr2/0/model_config.yaml
x logs/train/multiruns/hmr2/0/checkpoints/
x logs/train/multiruns/hmr2/0/checkpoints/epoch=35-step=1000000.ckpt
x logs/train/multiruns/hmr2/0/dataset_config.yaml
x data/
x data/SMPL_to_J19.pkl
x data/smpl_mean_params.npz
x data/smpl/
x data/smpl/SMPL_MALE.pkl
x data/smpl/SMPL_FEMALE.pkl
x data/smpl/SMPL_NEUTRAL.pkl
```

**Comment by SoftologyPro** [comment]
Yes, the extraction was the problem.  I was using command line 7zip.
For Windows you must use the tar command to extract it fully.
`tar -xvf hmr2_data.tar.gz`
Then the script runs fine.
