### ISSUE TITLE
EGL not working

### ISSUE THREAD

**Issue by samxu29** [shubham-goel/4D-Humans#87]
Followed all the setup step in the documents but can't seem to get working, am I missing the any dependency? 
I am trying to run on WSL with 3090ti

```
(4D-humans) ❯ python demo.py \
    --img_folder example_data/images \
    --out_folder demo_out \
    --batch_size=48 --side_view --save_mesh --full_frame
WARNING: You are using a SMPL model, with only 10 shape coefficients.
Traceback (most recent call last):
  File "/home/samxu/projects/hpe/4D-Humans/demo.py", line 154, in <module>
    main()
  File "/home/samxu/projects/hpe/4D-Humans/demo.py", line 31, in main
    model, model_cfg = load_hmr2(args.checkpoint)
  File "/home/samxu/projects/hpe/4D-Humans/hmr2/models/__init__.py", line 84, in load_hmr2
    model = HMR2.load_from_checkpoint(checkpoint_path, strict=False, cfg=model_cfg)
  File "/home/samxu/miniconda3/envs/4D-humans/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 1561, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/home/samxu/miniconda3/envs/4D-humans/lib/python3.10/site-packages/pytorch_lightning/core/saving.py", line 89, in _load_from_checkpoint
    model = _load_state(cls, checkpoint, strict=strict, **kwargs)
  File "/home/samxu/miniconda3/envs/4D-humans/lib/python3.10/site-packages/pytorch_lightning/core/saving.py", line 156, in _load_state
    obj = cls(**_cls_kwargs)
  File "/home/samxu/projects/hpe/4D-Humans/hmr2/models/hmr2.py", line 59, in __init__
    self.mesh_renderer = MeshRenderer(self.cfg, faces=self.smpl.faces)
  File "/home/samxu/projects/hpe/4D-Humans/hmr2/utils/mesh_renderer.py", line 50, in __init__
    self.renderer = pyrender.OffscreenRenderer(viewport_width=self.img_res,
  File "/home/samxu/miniconda3/envs/4D-humans/lib/python3.10/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/home/samxu/miniconda3/envs/4D-humans/lib/python3.10/site-packages/pyrender/offscreen.py", line 137, in _create
    egl_device = egl.get_device_by_index(device_id)
  File "/home/samxu/miniconda3/envs/4D-humans/lib/python3.10/site-packages/pyrender/platforms/egl.py", line 83, in get_device_by_index
    raise ValueError('Invalid device ID ({})'.format(device_id, len(devices)))
ValueError: Invalid device ID (0)
```

**Comment by Jack621-a** [comment]
I have the same problem. Have you solved it?

**Comment by xunzhi99** [comment]
I  also have the same problem. Have you solved it?

**Comment by LongDan15** [comment]
After installing libegl1-mesa-dev and mesa-utils using apt-get, the initial problem was resolved. 

```
sudo apt-get install libegl1-mesa-dev
sudo apt-get install mesa-utils

```

However, I encountered a new issue:
raise ValueError('Invalid device ID ({})'.format(device_id, len(devices)))
ValueError: Invalid device ID (0)
