### ISSUE TITLE
I keep getting similar error across many different environment with the demo.py "libEGL warning: MESA-LOADER: failed to open ..."

### ISSUE THREAD

**Issue by samxu29** [shubham-goel/4D-Humans#91]
```
libEGL warning: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)

libEGL warning: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)

Traceback (most recent call last):
  File "/4D-Humans/demo.py", line 167, in <module>
    main()
  File "/4D-Humans/demo.py", line 34, in main
    model, model_cfg = load_hmr2(args.checkpoint)
  File "/4D-Humans/hmr2/models/__init__.py", line 84, in load_hmr2
    model = HMR2.load_from_checkpoint(checkpoint_path, strict=False, cfg=model_cfg)
  File "/root/miniconda3/envs/4D-humans/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 1561, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/root/miniconda3/envs/4D-humans/lib/python3.10/site-packages/pytorch_lightning/core/saving.py", line 89, in _load_from_checkpoint
    model = _load_state(cls, checkpoint, strict=strict, **kwargs)
  File "/root/miniconda3/envs/4D-humans/lib/python3.10/site-packages/pytorch_lightning/core/saving.py", line 156, in _load_state
    obj = cls(**_cls_kwargs)
  File "/4D-Humans/hmr2/models/hmr2.py", line 59, in __init__
    self.mesh_renderer = MeshRenderer(self.cfg, faces=self.smpl.faces)
  File "/4D-Humans/hmr2/utils/mesh_renderer.py", line 49, in __init__
    self.renderer = pyrender.OffscreenRenderer(viewport_width=self.img_res,
  File "/root/miniconda3/envs/4D-humans/lib/python3.10/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/root/miniconda3/envs/4D-humans/lib/python3.10/site-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/root/miniconda3/envs/4D-humans/lib/python3.10/site-packages/pyrender/platforms/egl.py", line 177, in init_context
    assert eglInitialize(self._egl_display, major, minor)
  File "/root/miniconda3/envs/4D-humans/lib/python3.10/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "/root/miniconda3/envs/4D-humans/lib/python3.10/site-packages/OpenGL/error.py", line 228, in glCheckError
    raise GLError(
OpenGL.error.GLError: GLError(
        err = 12289,
        baseOperation = eglInitialize,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x7f4774565cc0>,
                c_long(0),
                c_long(0),
        ),
        result = 0
)
```

I didn't change any of the code, but I kept getting the same error as above, anyone have any idea.

Running on Ubuntu 22 with 11.8 cuda installed.

**Comment by samxu29** [comment]
So for someone who running into the same error, stop using conda. Created a environment with pyenv and it worked like a charm.
